media:
  - name: images
    label: 图片
    input: static/images
    output: /images
    extensions: [jpg, jpeg, png, webp, gif, svg]
  - name: files
    label: 附件
    input: static/files
    output: /files
    categories: [document]

content:
  - name: zh-posts
    label: 中文文章
    type: collection
    path: content/zh/posts
    format: toml-frontmatter
    fields:
      - name: lang
        label: 语言
        type: string
        default: zh
        required: true
      - name: title
        label: 标题
        type: string
        required: true
      - name: date
        label: 日期
        type: date
        required: true
      - name: draft
        label: 草稿
        type: boolean
        default: false
      - name: cover
        label: 封面
        type: object
        fields:
          - name: image
            label: 图片路径
            type: string
          - name: alt
            label: 图像说明
            type: string
          - name: caption
            label: 图片标题
            type: string
      - name: body
        label: 正文
        type: text
        required: true
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [title, date, draft, lang]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc

  - name: ja-posts
    label: 日本語記事
    type: collection
    path: content/ja/posts
    format: toml-frontmatter
    fields:
      - name: lang
        label: 言語
        type: string
        default: ja
        required: true
      - name: title
        label: タイトル
        type: string
        required: true
      - name: date
        label: 日付
        type: date
        required: true
      - name: draft
        label: 下書き
        type: boolean
        default: false
      - name: cover
        label: カバー
        type: object
        fields:
          - name: image
            label: 画像パス
            type: string
          - name: alt
            label: 画像説明
            type: string
          - name: caption
            label: キャプション
            type: string
      - name: body
        label: 本文
        type: text
        required: true
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [title, date, draft, lang]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc

  - name: en-posts
    label: English Posts
    type: collection
    path: content/en/posts
    format: toml-frontmatter
    fields:
      - name: lang
        label: Language
        type: string
        default: en
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: cover
        label: Cover
        type: object
        fields:
          - name: image
            label: Image path
            type: string
          - name: alt
            label: Alt text
            type: string
          - name: caption
            label: Caption
            type: string
      - name: body
        label: Body
        type: text
        required: true
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [title, date, draft, lang]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc

components:
  cover:
    label: 通用封面
    type: object
    fields:
      - name: image
        label: 图片路径
        type: string
      - name: alt
        label: 图像说明
        type: string
      - name: caption
        label: 图片标题
        type: string

settings:
  content:
    merge: true
